<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\PatientEnrollmentRecord;
class PatientEnrollmentRecordController extends Controller
{
    public static function index(){
        $patient = PatientEnrollmentRecord::get();
        return view('pages.patientEnrollmentRecord.index')->with(['patient' => $patient]);
    }

    public static function store(Request $request){

        // Validate the request
        $request->validate([
            'inp_ln' => 'required|string|max:255',
            'inp_fn' => 'required|string|max:255',
            'inp_mn' => 'required|string|max:255',
            'inp_extension' => 'required|string|max:255',
            'inp_region' => 'required|string|max:255',
            'inp_pwmnmw' => 'required|string|max:255',
            'inp_mnni' => 'required|string|max:255',
            'inp_ca' => 'required|string|max:255',
            'inp_mne' => 'nullable|string|max:20',
            'inp_bd' => 'required|string|max:2555',
            'inp_bp' => 'required|string|max:255',
            'inp_age' =>'required|string|max:20',
            'inp_gender' => 'required|string|max:255',
            'inp_civil' => 'required|string|max:255',
            'inp_family ' => 'nullable|string|max:255',
            'inp_bt' => 'required|string|max:255',
            'inp_religion' => 'required|string|max:255',
            'inp_pm' => 'required|string|max:255',
            'inp_pmt' => 'required|string|max:255',
            'inp_pn' => 'nullable|string|max:20',
            'inp_pme' => 'required|string|max:255',
            'inp_kr' => 'required|string|max:255',
            'inp_kf' => 'required|string|max:255',
            'inp_es' => 'required|string|max:255',
            'inp_dn' => 'required|string|max:255',
            'inp_4m' => 'required|string|max:255',
            'inp_fhn' => 'required|integer|max:255',
            'inp_hne' => 'required|integer|max:255',
            'inp_ea' => 'required|string|max:255',
            'inp_bpe' => 'required|integer|max:255',
            'inp_hr' => 'required|integer|max:255',
            'inp_rr' => 'required|integer|max:255',
            'inp_pr' => 'required|integer|max:255',
            'inp_temp' => 'required|integer|max:255',
            'inp_height' => 'required|integer|max:255',
            'inp_weight' => 'nullable|string|max:255',
            'inp_os' => 'required|integer|max:255',
            'inp_ab' => 'required|string|max:255',
            'inp_lne' => 'required|string|max:255',
            'inp_fne' => 'required|string|max:255',
            'inp_suffix' => 'required|string|max:255',
            'inp_mns' => 'required|string|max:255',
            'inp_relationship' => 'required|string|max:255',
            'inp_dob' => 'required|string|max:255',
            'inp_pc' => 'nullable|string|max:20',
            'inp_regions' => 'required|string|max:255',
            'inp_province' => 'required|string|max:255',
            'inp_com' => 'required|string|max:255',
            'inp_barangay' => 'required|string|max:255',
            'inp_fh' => 'required|string|max:255',
            'inp_pmh' => 'required|string|max:255',
            'inp_psh' => 'required|string|max:255',
            'inp_fcci' => 'required|string|max:255',
            'inp_fptt' => 'required|string|max:255',
            'inp_f5yo' => 'required|string|max:255',
            'inp_smoking' => 'required|string|max:255',
            'inp_sa' => 'required|string|max:255',
            'inp_alcohol' => 'required|string|max:255',
            'inp_id' => 'required|string|max:255',
            'inp_menarche' => 'required|string|max:255',
            'inp_lmp' => 'required|string|max:255',
            'inp_osi' => 'required|string|max:255',
            'inp_menopause' => 'required|string|max:255',
            'inp_fpm' => 'required|string|max:255',
            'inp_gop' => 'required|integer|max:255',
            'inp_pod' => 'required|integer|max:255',
            'inp_tod' => 'required|string|max:2555',
            'inp_noft' => 'required|integer|max:255',
            'inp_nop' => 'required|integer|max:255',
            'inp_noa' => 'required|integer|max:255',
            'inp_nolc' => 'required|integer|max:255',
            
        ]);

        // Save customer record
        PatientEnrollmentRecord::create([
            'per_last_name'=> $request->inp_ln,
            'per_first_name'=> $request->inp_fn,
            'per_middle_name'=> $request->inp_mn,
            'per_extension'=> $request->inp_extension,
            'per_region'=> $request->inp_region,
            'per_maiden_name'=> $request->inp_pwmnmw,
            'per_mothers_name'=> $request->inp_mnni,
            'per_complete_address'=> $request->inp_ca,
            'per_mobile_no'=> $request->inp_mne,
            'per_birth_date'=> $request->inp_bd,
            'per_birth_place'=> $request->inp_bp,
            'per_age'=> $request->inp_age,
            'per_gender'=> $request->inp_gender,
            'per_civil'=> $request->inp_civil,
            'per_family'=> $request->inp_family,
            'per_blood_type'=> $request->inp_bt,
            'per_religion'=> $request->inp_religion,
            'per_phic_member'=> $request->inp_pm,
            'per_philhealth_member_type'=> $request->inp_pmt,
            'per_philhealth_number'=> $request->inp_pn,
            'per_philhealth_membership'=> $request->inp_pme,
            'per_konsulta_registered'=> $request->inp_kr,
            'per_konsulta_facility' => $request->inp_kf,
            'per_employment_status' => $request->inp_es,
            'per_dswd_nhts' => $request->inp_dn,
            'per_4ps_member' => $request->inp_4m,
            'per_facility_household_no' => $request->inp_fhn,
            'per_household_no' => $request->inp_hne,
            'per_educational_attainment' => $request->inp_ea,
            'per_bp' => $request->inp_bpe,
            'per_hr' => $request->inp_hr,
            'per_rr'=> $request->inp_rr,
            'per_pulse_rate' => $request->inp_pr,
            'per_temp' => $request->inp_temp,
            'per_height' => $request->inp_height,
            'per_weight' => $request->inp_weight,
            'per_ox_sat' => $request->inp_os,
            'per_administered_by' => $request->inp_ab,
            'per_last_name_duplicate' => $request->inp_lne,
            'per_first_name_duplicate' => $request->inp_fne,
            'per_suffix' => $request->inp_suffix,
            'per_middle_name_duplicate' => $request->inp_mns,
            'per_relationship' => $request->inp_relationship,
            'per_date_of_birth' => $request->inp_dob,
            'per_postal_code' => $request->inp_pc,
            'per_regions' => $request->inp_regions,
            'per_province' => $request->inp_province,
            'per_city_or_municipality' => $request->inp_com,
            'per_barangay' => $request->inp_barangay,
            'per_family_history' => $request->inp_fh,
            'per_past_medical_history' => $request->inp_pmh,
            'per_past_surgical_history' => $request->inp_psh,
            'per_children_immunized' => $request->inp_fcci,
            'per_pregnant_tetanus_toxoid' => $request->inp_fptt,
            'per_covid_vaccine_5_years_above' => $request->inp_f5yo,
            'per_smoking' => $request->inp_smoking,
            'per_sexually_active' => $request->inp_sa,
            'per_alcohol' => $request->inp_alcohol,
            'per_illicit_drugs' => $request->inp_id,
            'per_menarche' => $request->inp_menarche,
            'per_last_menstrual_period' => $request->inp_lmp,
            'per_onset_sexual_intercourse' => $request->inp_osi,
            'per_menopause' => $request->inp_menopause,
            'per_family_planning_method' => $request->inp_fpm,
            'per_gravity' => $request->inp_gop,
            'per_parity' => $request->inp_pod,
            'per_type_of_delivery' => $request->inp_tod,
            'per_no_of_full_term' => $request->inp_noft,
            'per_no_of_premature' => $request->inp_nop,
            'per_no_of_abortion' => $request->inp_noa,
            'per_no_of_living_children' => $request->inp_nolc,
        ]);

        // Redirect back with success message
        return redirect()->back()->with('success', 'Patient Enrollment Record added successfully!');
    }
}

